services:
  db:
    image: mysql:8.0
    container_name: wordpress_db
    restart: unless-stopped
    env_file: .env
    environment:
      - MYSQL_DATABASE=wordpress
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - wordpress

  wordpress:
    depends_on:
      - db
    image: wordpress:6.4-apache
    container_name: wordpress_site
    restart: unless-stopped
    env_file: .env
    environment:
      - WORDPRESS_DB_HOST=db:3306
      - WORDPRESS_DB_NAME=wordpress
    volumes:
      - wordpress_data:/var/www/html
      - ./plugins:/var/www/html/wp-content/plugins/custom
      - ./themes:/var/www/html/wp-content/themes/custom
    ports:
      - "8080:80"
    networks:
      - wordpress

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    container_name: wordpress_phpmyadmin
    restart: unless-stopped
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: rootpassword
    networks:
      - wordpress

volumes:
  db_data: {}
  wordpress_data: {}

networks:
  wordpress:
    driver: bridge